---
- name: Uninstall K3s
  hosts: pi-0
  become: yes
  tasks:
    - name: Check if K3s is installed
      command: which k3s
      register: k3s_installed
      ignore_errors: yes

    - name: Uninstall K3s
      shell: /usr/local/bin/k3s-uninstall.sh
      when: k3s_installed.rc == 0

    - name: Remove K3s data directory
      file:
        path: /var/lib/rancher/k3s
        state: absent
      when: k3s_installed.rc == 0

    - name: Remove K3s binaries
      file:
        path: /usr/local/bin/k3s
        state: absent
      when: k3s_installed.rc == 0
